server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${GIT_URI}
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"